```{r}
library(tidyverse)
library(readr)
library(arules)
library(arulesViz)
```

```{r}
BX_Book_Ratings <- read_delim("BX-Book-Ratings.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
BX_Books <- read_delim("BX-Books.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)
BX_Users <- read_delim("BX-Users.csv", ";", 
    escape_double = FALSE, trim_ws = TRUE)
```


```{r}
books <- BX_Books %>%
  select(ISBN, `Book-Title`, `Book-Author`, `Year-Of-Publication`, Publisher)
rm(BX_Books)
users <- BX_Users %>%
  mutate(Age= as.numeric(Age))
rm(BX_Users)
ratings <- BX_Book_Ratings %>%
  left_join(books)
rm(BX_Book_Ratings)
ratings <- ratings %>%
  filter(!is.na(`Book-Title`))

users <- users %>%
  filter(!is.na(Age)) %>%
  mutate(country = str_remove(Location,".*,")) %>%
  filter(country != "")
all <- ratings %>%
  left_join(users) %>%
  select(-Location)
write_csv(all, "all.csv")
```

---
title: "Beispiel-Notebook EDA / Data Science 3. Session"
output:
  html_document:
    df_print: paged
---

```{r}
all <- read_csv("all.csv")
```

```{r message=FALSE}
i <- split(all$`Book-Title`,all$`User-ID`)
txn <- as(i, "transactions")
basket_rules <- apriori(txn, parameter = list(sup = 0.0015, conf = 0.001, minlen=2, target="rules"))
```



```{r}
myRules_Direct <- as(basket_rules, "data.frame")
basket_rules_hi <- head(basket_rules, by ="lift",100)
head(myRules_Direct, 20)
```


```{r}
plot(basket_rules_hi, method="graph", main="Books")
```


```{r}
plot(basket_rules_hi, method="graph", main="Books", engine="interactive")
```